name: h-cli-tool
version: 0.1.0

ghc-options: -Wall -O2

executables:
  h:
    main: H.hs
    dependencies:
      - ansi-wl-pprint
      - base
      - deepseq
      - foldl
      - ghc
      - ghc-paths
      - ghc-prim
      - optparse-applicative
      - text
      - turtle
